import { SoundboardConfig } from './types';

/**
 * ============================================================================
 * HOUSE STIM SOUNDBOARD CONFIGURATION
 * ============================================================================
 *
 * All stims and clips are configured here in code.
 * - To add more clips: Add an item to the `sounds` array.
 * - For YouTube clips: set `youtubeUrl: "https://youtu.be/..."`.
 * - For TikTok clips: set `tiktokUrl: "https://www.tiktok.com/@.../video/..."` (or short link `https://vm.tiktok.com/...`).
 * - For local audio files: place in `/public/sounds/` and set `audioSrc: "/sounds/clip.mp3"`.
 * ============================================================================
 */

export const SOUNDBOARD_CONFIG: SoundboardConfig = {
  appTitle: 'House Stims',
  appSubtitle: 'Tap to play',
  allowPolyphony: false,
  sounds: [
    {
      id: 'yt-get-out',
      title: 'Get Out!',
      description: 'Classic comedic house stim shout clip',
      youtubeUrl: 'https://youtu.be/iRnzJ6gtAeU?list=PLdUrbQOZtGn0',
      category: 'House Stims',
      color: 'rose',
    },
    {
      id: 'yt-a-steak',
      title: 'A Steak!',
      description: 'Enthusiastic food stim moment',
      youtubeUrl: 'https://youtu.be/IG-hbYepJuo?list=PLdUrbQOZtGn0',
      category: 'Invincible',
      color: 'amber',
    },
    {
      id: 'yt-beautiful-woman-intro',
      title: 'Eli, 35, Beautiful Woman (Intro)',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/xCsL-3qhI1c',
      startTime: 4134,
      endTime: 4139,
      category: 'Unc',
      color: 'violet',
    },
    {
      id: 'yt-unc-dance',
      title: 'UNC Dance',
      description: 'Hype dance rhythm house stim',
      youtubeUrl: 'https://youtu.be/bpkDlz4ZwJU?list=PLdUrbQOZtGn0',
      category: 'Unc',
      color: 'cyan',
    },
    {
      id: 'yt-know-when-to-hold-them',
      title: 'Know When to Hold Them',
      description: 'Kenny Rogers Gambler house singalong clip',
      youtubeUrl: 'https://youtu.be/yPqvV7VbhCs?list=PLdUrbQOZtGn0',
      startTime: 28,
      endTime: 39.3,
      category: 'Unc',
      color: 'emerald',
    },
    {
      id: 'yt-can-i-sing-it-bartender',
      title: 'Can I Sing It, The Bartender',
      description: 'Lively vocal bartender stim song',
      youtubeUrl: 'https://youtu.be/Qdc2cgn09fQ?list=PLdUrbQOZtGn0',
      category: 'Unc',
      color: 'orange',
    },
    {
      id: 'yt-a-black-one',
      title: 'A Black One',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/I04LeOk8d_I?list=PLdUrbQOZtGn0',
      startTime: 7,
      endTime: 10,
      category: 'House Stims',
      color: 'black',
    },
    {
      id: 'yt-one-small-exception',
      title: 'One Small Exception',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/17GI4l3_35Q?list=PLdUrbQOZtGn0',
      startTime: 0,
      endTime: 8,
      category: 'House Stims',
      color: 'black',
    },
    {
      id: 'tiktok-the-inside-scoop',
      title: 'The Inside Scoop',
      description: 'House stim clip',
      tiktokUrl: 'https://www.tiktok.com/@thetigerentertainment777/video/7682884362580397334',
      startTime: 0,
      endTime: 8.1,
      thumbnailUrl: '/sounds/the-inside-scoop.jpg',
      category: 'House Stims',
      color: 'amber',
    },
    {
      id: 'tiktok-243486',
      title: 'Yeah, he has',
      description: 'House stim clip',
      tiktokUrl: 'https://www.tiktok.com/@cbsnews/video/7675088620314692877',
      startTime: 0,
      endTime: 9,
      category: 'House Stims',
      color: 'amber',
    },
    {
      id: 'yt-5dg295ILEDc',
      title: 'Doug Chuglas',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/5dg295ILEDc',
      startTime: 10,
      category: 'Invincible',
      color: 'amber',
    },
    {
      id: 'yt-HgKSqeGdyLA',
      title: 'Who, Apocalypse?',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/HgKSqeGdyLA',
      startTime: 4.1,
      endTime: 6.9,
      category: 'X-Men',
      color: 'amber',
    },
    {
      id: 'yt-Unik8Q0wnk0',
      title: 'Say That Again',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/Unik8Q0wnk0',
      category: 'House Stims',
      color: 'amber',
    },
    {
      id: 'yt-swfxOf5w_VM',
      title: 'Enough',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/swfxOf5w_VM',
      startTime: 64,
      endTime: 75,
      category: 'X-Men',
      color: 'amber',
    },
        {
      id: 'yt-Mi5SyKhCla8',
      title: 'Nine',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/Mi5SyKhCla8',
      startTime: 13.5,
      endTime: 23.5,
      category: 'X-Men',
      color: 'amber',
    },
    {
      id: 'yt-QewzW_xpDfA',
      title: 'I Can\'t Touch You Remy',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/QewzW_xpDfA',
      startTime: 48.2,
      endTime: 50.3,
      category: 'X-Men',
      color: 'amber',
    },
        {
      id: 'yt-book-tew',
      title: 'It\'s a Book Tew',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/QIn7Utyx0D0',
      startTime: 16.2,
      category: 'House Stims',
      color: 'amber',
    },
        {
      id: 'yt-fhIT3UEGLFY',
      title: 'Are You Sure?',
      description: 'House stim clip',
      youtubeUrl: 'https://youtu.be/fhIT3UEGLFY',
      category: 'Invincible',
      color: 'amber',
    },
  ],
};
